export const MARRIAGE_STATUS_OPTION = [
  { value: "Married", label: "Married" },
  { value: "Unmarried", label: "Unmarried" },
  { value: "Divorce", label: "Divorce" },
  { value: "Widowed", label: "Widowed" },
  { value: "Separated", label: "Separated" },
];
export const HIGHEST_QUALIFICATION_OPTION = [
  { value: "Doctorate", label: "Doctorate" },
  { value: "PHD", label: "PHD" },
  { value: "Master Degree", label: "Master Degree" },
  { value: "Bachelor Degree", label: "Bachelor Degree" },
  { value: "Diploma after 12th", label: "Diploma after 12th" },
  { value: "Diploma after 10th", label: "Diploma after 10th" },
  { value: "12th", label: "12th" },
  { value: "10th", label: "10th" },
];

export const QUALIFICATION_TYPE_OPTION = [
  { value: "Corressponding", label: "Corressponding" },
  { value: "Regular", label: "Regular" },
];

export const YES_NO_OPTION = [
  { value: "Yes", label: "Yes" },
  { value: "No", label: "No" },
];
export const ACCEPPTED_DOC_TYPE = [
  ".jpg,",
  ".png,",
  ".jpeg,",
  ".gif,",
  ".bmp,",
  ".pdf,",
  ".doc",
  ".docx",
  ".tif,",
  ".tiff|image/*",
];

export const CONSULTANT_OPTIONS = [
  { value: "Afreen", label: "Afreen" },
  { value: "Akash", label: "Akash" },
  { value: "Anjali", label: "Anjali" },
  { value: "Esha", label: "Esha" },
  { value: "Geetanjali", label: "Geetanjali" },
  { value: "Hamid", label: "Hamid" },
  { value: "Jyotika", label: "Jyotika" },
  { value: "Kirti", label: "Kirti" },
  { value: "Krishna", label: "Krishna" },
  { value: "Niharika", label: "Niharika" },
  { value: "Nisha", label: "Nisha" },
  { value: "Nishant", label: "Nishant" },
  { value: "Pooja", label: "Pooja" },
  { value: "Pradeep", label: "Pradeep" },
  { value: "Radhika", label: "Radhika" },
  { value: "Rahul", label: "Rahul" },
  { value: "Rohit", label: "Rohit" },
  { value: "Sahil", label: "Sahil" },
  { value: "Shaurya", label: "Shaurya" },
  { value: "Shreya", label: "Shreya" },
  { value: "Sonali", label: "Sonali" },
  { value: "Sumit", label: "Sumit" },
  { value: "Twarita", label: "Twarita" },
  { value: "Himanshi", label: "Himanshi" },
  { value: "Laxmi", label: "Laxmi" },
];

export const COUNTRY_CODES = [
  {
    name: "Afghanistan (‫افغانستان‬‎)",
    countryCode: "AF",
    dialCode: "93",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/AF.svg",
  },
  {
    name: "Albania (Shqipëri)",
    countryCode: "AL",
    dialCode: "355",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/AL.svg",
  },
  {
    name: "Algeria (‫الجزائر‬‎)",
    countryCode: "DZ",
    dialCode: "213",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/DZ.svg",
  },
  {
    name: "American Samoa",
    countryCode: "AS",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/AS.svg",
  },
  {
    name: "Andorra",
    countryCode: "AD",
    dialCode: "376",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/AD.svg",
  },
  {
    name: "Angola",
    countryCode: "AO",
    dialCode: "244",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/AO.svg",
  },
  {
    name: "Anguilla",
    countryCode: "AI",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/AI.svg",
  },
  {
    name: "Antigua and Barbuda",
    countryCode: "AG",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/AG.svg",
  },
  {
    name: "Argentina",
    countryCode: "AR",
    dialCode: "54",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/AR.svg",
  },
  {
    name: "Armenia (Հայաստան)",
    countryCode: "AM",
    dialCode: "374",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/AM.svg",
  },
  {
    name: "Aruba",
    countryCode: "AW",
    dialCode: "297",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/AW.svg",
  },
  {
    name: "Ascension Island",
    countryCode: "AC",
    dialCode: "247",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/AC.svg",
  },
  {
    name: "Australia",
    countryCode: "AU",
    dialCode: "61",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/AU.svg",
  },
  {
    name: "Austria (Österreich)",
    countryCode: "AT",
    dialCode: "43",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/AT.svg",
  },
  {
    name: "Azerbaijan (Azərbaycan)",
    countryCode: "AZ",
    dialCode: "994",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/AZ.svg",
  },
  {
    name: "Bahamas",
    countryCode: "BS",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BS.svg",
  },
  {
    name: "Bahrain (‫البحرين‬‎)",
    countryCode: "BH",
    dialCode: "973",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BH.svg",
  },
  {
    name: "Bangladesh (বাংলাদেশ)",
    countryCode: "BD",
    dialCode: "880",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BD.svg",
  },
  {
    name: "Barbados",
    countryCode: "BB",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BB.svg",
  },
  {
    name: "Belarus (Беларусь)",
    countryCode: "BY",
    dialCode: "375",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BY.svg",
  },
  {
    name: "Belgium (België)",
    countryCode: "BE",
    dialCode: "32",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BE.svg",
  },
  {
    name: "Belize",
    countryCode: "BZ",
    dialCode: "501",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BZ.svg",
  },
  {
    name: "Benin (Bénin)",
    countryCode: "BJ",
    dialCode: "229",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BJ.svg",
  },
  {
    name: "Bermuda",
    countryCode: "BM",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BM.svg",
  },
  {
    name: "Bhutan (འབྲུག)",
    countryCode: "BT",
    dialCode: "975",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BT.svg",
  },
  {
    name: "Bolivia",
    countryCode: "BO",
    dialCode: "591",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BO.svg",
  },
  {
    name: "Bosnia and Herzegovina (Босна и Херцеговина)",
    countryCode: "BA",
    dialCode: "387",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BA.svg",
  },
  {
    name: "Botswana",
    countryCode: "BW",
    dialCode: "267",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BW.svg",
  },
  {
    name: "Brazil (Brasil)",
    countryCode: "BR",
    dialCode: "55",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BR.svg",
  },
  {
    name: "British Indian Ocean Territory",
    countryCode: "IO",
    dialCode: "246",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/IO.svg",
  },
  {
    name: "British Virgin Islands",
    countryCode: "VG",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/VG.svg",
  },
  {
    name: "Brunei",
    countryCode: "BN",
    dialCode: "673",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BN.svg",
  },
  {
    name: "Bulgaria (България)",
    countryCode: "BG",
    dialCode: "359",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BG.svg",
  },
  {
    name: "Burkina Faso",
    countryCode: "BF",
    dialCode: "226",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BF.svg",
  },
  {
    name: "Burundi (Uburundi)",
    countryCode: "BI",
    dialCode: "257",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BI.svg",
  },
  {
    name: "Cambodia (កម្ពុជា)",
    countryCode: "KH",
    dialCode: "855",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/KH.svg",
  },
  {
    name: "Cameroon (Cameroun)",
    countryCode: "CM",
    dialCode: "237",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CM.svg",
  },
  {
    name: "Canada",
    countryCode: "CA",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CA.svg",
  },
  {
    name: "Cape Verde (Kabu Verdi)",
    countryCode: "CV",
    dialCode: "238",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CV.svg",
  },
  {
    name: "Caribbean Netherlands",
    countryCode: "BQ",
    dialCode: "599",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BQ.svg",
  },
  {
    name: "Cayman Islands",
    countryCode: "KY",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/KY.svg",
  },
  {
    name: "Central African Republic (République centrafricaine)",
    countryCode: "CF",
    dialCode: "236",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CF.svg",
  },
  {
    name: "Chad (Tchad)",
    countryCode: "TD",
    dialCode: "235",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/TD.svg",
  },
  {
    name: "Chile",
    countryCode: "CL",
    dialCode: "56",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CL.svg",
  },
  {
    name: "China (中国)",
    countryCode: "CN",
    dialCode: "86",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CN.svg",
  },
  {
    name: "Christmas Island",
    countryCode: "CX",
    dialCode: "61",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CX.svg",
  },
  {
    name: "Cocos (Keeling) Islands",
    countryCode: "CC",
    dialCode: "61",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CC.svg",
  },
  {
    name: "Colombia",
    countryCode: "CO",
    dialCode: "57",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CO.svg",
  },
  {
    name: "Comoros (‫جزر القمر‬‎)",
    countryCode: "KM",
    dialCode: "269",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/KM.svg",
  },
  {
    name: "Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)",
    countryCode: "CD",
    dialCode: "243",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CD.svg",
  },
  {
    name: "Congo (Republic) (Congo-Brazzaville)",
    countryCode: "CG",
    dialCode: "242",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CG.svg",
  },
  {
    name: "Cook Islands",
    countryCode: "CK",
    dialCode: "682",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CK.svg",
  },
  {
    name: "Costa Rica",
    countryCode: "CR",
    dialCode: "506",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CR.svg",
  },
  {
    name: "Côte d’Ivoire",
    countryCode: "CI",
    dialCode: "225",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CI.svg",
  },
  {
    name: "Croatia (Hrvatska)",
    countryCode: "HR",
    dialCode: "385",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/HR.svg",
  },
  {
    name: "Cuba",
    countryCode: "CU",
    dialCode: "53",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CU.svg",
  },
  {
    name: "Curaçao",
    countryCode: "CW",
    dialCode: "599",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CW.svg",
  },
  {
    name: "Cyprus (Κύπρος)",
    countryCode: "CY",
    dialCode: "357",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CY.svg",
  },
  {
    name: "Czech Republic (Česká republika)",
    countryCode: "CZ",
    dialCode: "420",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CZ.svg",
  },
  {
    name: "Denmark (Danmark)",
    countryCode: "DK",
    dialCode: "45",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/DK.svg",
  },
  {
    name: "Djibouti",
    countryCode: "DJ",
    dialCode: "253",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/DJ.svg",
  },
  {
    name: "Dominica",
    countryCode: "DM",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/DM.svg",
  },
  {
    name: "Dominican Republic (República Dominicana)",
    countryCode: "DO",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/DO.svg",
  },
  {
    name: "Ecuador",
    countryCode: "EC",
    dialCode: "593",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/EC.svg",
  },
  {
    name: "Egypt (‫مصر‬‎)",
    countryCode: "EG",
    dialCode: "20",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/EG.svg",
  },
  {
    name: "El Salvador",
    countryCode: "SV",
    dialCode: "503",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SV.svg",
  },
  {
    name: "Equatorial Guinea (Guinea Ecuatorial)",
    countryCode: "GQ",
    dialCode: "240",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GQ.svg",
  },
  {
    name: "Eritrea",
    countryCode: "ER",
    dialCode: "291",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/ER.svg",
  },
  {
    name: "Estonia (Eesti)",
    countryCode: "EE",
    dialCode: "372",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/EE.svg",
  },
  {
    name: "Eswatini",
    countryCode: "SZ",
    dialCode: "268",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SZ.svg",
  },
  {
    name: "Ethiopia",
    countryCode: "ET",
    dialCode: "251",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/ET.svg",
  },
  {
    name: "Falkland Islands (Islas Malvinas)",
    countryCode: "FK",
    dialCode: "500",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/FK.svg",
  },
  {
    name: "Faroe Islands (Føroyar)",
    countryCode: "FO",
    dialCode: "298",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/FO.svg",
  },
  {
    name: "Fiji",
    countryCode: "FJ",
    dialCode: "679",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/FJ.svg",
  },
  {
    name: "Finland (Suomi)",
    countryCode: "FI",
    dialCode: "358",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/FI.svg",
  },
  {
    name: "France",
    countryCode: "FR",
    dialCode: "33",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/FR.svg",
  },
  {
    name: "French Guiana (Guyane française)",
    countryCode: "GF",
    dialCode: "594",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GF.svg",
  },
  {
    name: "French Polynesia (Polynésie française)",
    countryCode: "PF",
    dialCode: "689",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/PF.svg",
  },
  {
    name: "Gabon",
    countryCode: "GA",
    dialCode: "241",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GA.svg",
  },
  {
    name: "Gambia",
    countryCode: "GM",
    dialCode: "220",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GM.svg",
  },
  {
    name: "Georgia (საქართველო)",
    countryCode: "GE",
    dialCode: "995",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GE.svg",
  },
  {
    name: "Germany (Deutschland)",
    countryCode: "DE",
    dialCode: "49",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/DE.svg",
  },
  {
    name: "Ghana (Gaana)",
    countryCode: "GH",
    dialCode: "233",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GH.svg",
  },
  {
    name: "Gibraltar",
    countryCode: "GI",
    dialCode: "350",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GI.svg",
  },
  {
    name: "Greece (Ελλάδα)",
    countryCode: "GR",
    dialCode: "30",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GR.svg",
  },
  {
    name: "Greenland (Kalaallit Nunaat)",
    countryCode: "GL",
    dialCode: "299",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GL.svg",
  },
  {
    name: "Grenada",
    countryCode: "GD",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GD.svg",
  },
  {
    name: "Guadeloupe",
    countryCode: "GP",
    dialCode: "590",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GP.svg",
  },
  {
    name: "Guam",
    countryCode: "GU",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GU.svg",
  },
  {
    name: "Guatemala",
    countryCode: "GT",
    dialCode: "502",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GT.svg",
  },
  {
    name: "Guernsey",
    countryCode: "GG",
    dialCode: "44",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GG.svg",
  },
  {
    name: "Guinea (Guinée)",
    countryCode: "GN",
    dialCode: "224",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GN.svg",
  },
  {
    name: "Guinea-Bissau (Guiné Bissau)",
    countryCode: "GW",
    dialCode: "245",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GW.svg",
  },
  {
    name: "Guyana",
    countryCode: "GY",
    dialCode: "592",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GY.svg",
  },
  {
    name: "Haiti",
    countryCode: "HT",
    dialCode: "509",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/HT.svg",
  },
  {
    name: "Honduras",
    countryCode: "HN",
    dialCode: "504",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/HN.svg",
  },
  {
    name: "Hong Kong (香港)",
    countryCode: "HK",
    dialCode: "852",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/HK.svg",
  },
  {
    name: "Hungary (Magyarország)",
    countryCode: "HU",
    dialCode: "36",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/HU.svg",
  },
  {
    name: "Iceland (Ísland)",
    countryCode: "IS",
    dialCode: "354",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/IS.svg",
  },
  {
    name: "India (भारत)",
    countryCode: "IN",
    dialCode: "91",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/IN.svg",
  },
  {
    name: "Indonesia",
    countryCode: "ID",
    dialCode: "62",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/ID.svg",
  },
  {
    name: "Iran (‫ایران‬‎)",
    countryCode: "IR",
    dialCode: "98",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/IR.svg",
  },
  {
    name: "Iraq (‫العراق‬‎)",
    countryCode: "IQ",
    dialCode: "964",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/IQ.svg",
  },
  {
    name: "Ireland",
    countryCode: "IE",
    dialCode: "353",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/IE.svg",
  },
  {
    name: "Isle of Man",
    countryCode: "IM",
    dialCode: "44",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/IM.svg",
  },
  {
    name: "Israel (‫ישראל‬‎)",
    countryCode: "IL",
    dialCode: "972",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/IL.svg",
  },
  {
    name: "Italy (Italia)",
    countryCode: "IT",
    dialCode: "39",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/IT.svg",
  },
  {
    name: "Jamaica",
    countryCode: "JM",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/JM.svg",
  },
  {
    name: "Japan (日本)",
    countryCode: "JP",
    dialCode: "81",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/JP.svg",
  },
  {
    name: "Jersey",
    countryCode: "JE",
    dialCode: "44",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/JE.svg",
  },
  {
    name: "Jordan (‫الأردن‬‎)",
    countryCode: "JO",
    dialCode: "962",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/JO.svg",
  },
  {
    name: "Kazakhstan (Казахстан)",
    countryCode: "KZ",
    dialCode: "7",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/KZ.svg",
  },
  {
    name: "Kenya",
    countryCode: "KE",
    dialCode: "254",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/KE.svg",
  },
  {
    name: "Kiribati",
    countryCode: "KI",
    dialCode: "686",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/KI.svg",
  },
  {
    name: "Kosovo",
    countryCode: "XK",
    dialCode: "383",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/XK.svg",
  },
  {
    name: "Kuwait (‫الكويت‬‎)",
    countryCode: "KW",
    dialCode: "965",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/KW.svg",
  },
  {
    name: "Kyrgyzstan (Кыргызстан)",
    countryCode: "KG",
    dialCode: "996",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/KG.svg",
  },
  {
    name: "Laos (ລາວ)",
    countryCode: "LA",
    dialCode: "856",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/LA.svg",
  },
  {
    name: "Latvia (Latvija)",
    countryCode: "LV",
    dialCode: "371",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/LV.svg",
  },
  {
    name: "Lebanon (‫لبنان‬‎)",
    countryCode: "LB",
    dialCode: "961",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/LB.svg",
  },
  {
    name: "Lesotho",
    countryCode: "LS",
    dialCode: "266",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/LS.svg",
  },
  {
    name: "Liberia",
    countryCode: "LR",
    dialCode: "231",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/LR.svg",
  },
  {
    name: "Libya (‫ليبيا‬‎)",
    countryCode: "LY",
    dialCode: "218",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/LY.svg",
  },
  {
    name: "Liechtenstein",
    countryCode: "LI",
    dialCode: "423",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/LI.svg",
  },
  {
    name: "Lithuania (Lietuva)",
    countryCode: "LT",
    dialCode: "370",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/LT.svg",
  },
  {
    name: "Luxembourg",
    countryCode: "LU",
    dialCode: "352",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/LU.svg",
  },
  {
    name: "Macau (澳門)",
    countryCode: "MO",
    dialCode: "853",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MO.svg",
  },
  {
    name: "Madagascar (Madagasikara)",
    countryCode: "MG",
    dialCode: "261",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MG.svg",
  },
  {
    name: "Malawi",
    countryCode: "MW",
    dialCode: "265",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MW.svg",
  },
  {
    name: "Malaysia",
    countryCode: "MY",
    dialCode: "60",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MY.svg",
  },
  {
    name: "Maldives",
    countryCode: "MV",
    dialCode: "960",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MV.svg",
  },
  {
    name: "Mali",
    countryCode: "ML",
    dialCode: "223",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/ML.svg",
  },
  {
    name: "Malta",
    countryCode: "MT",
    dialCode: "356",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MT.svg",
  },
  {
    name: "Marshall Islands",
    countryCode: "MH",
    dialCode: "692",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MH.svg",
  },
  {
    name: "Martinique",
    countryCode: "MQ",
    dialCode: "596",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MQ.svg",
  },
  {
    name: "Mauritania (‫موريتانيا‬‎)",
    countryCode: "MR",
    dialCode: "222",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MR.svg",
  },
  {
    name: "Mauritius (Moris)",
    countryCode: "MU",
    dialCode: "230",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MU.svg",
  },
  {
    name: "Mayotte",
    countryCode: "YT",
    dialCode: "262",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/YT.svg",
  },
  {
    name: "Mexico (México)",
    countryCode: "MX",
    dialCode: "52",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MX.svg",
  },
  {
    name: "Micronesia",
    countryCode: "FM",
    dialCode: "691",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/FM.svg",
  },
  {
    name: "Moldova (Republica Moldova)",
    countryCode: "MD",
    dialCode: "373",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MD.svg",
  },
  {
    name: "Monaco",
    countryCode: "MC",
    dialCode: "377",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MC.svg",
  },
  {
    name: "Mongolia (Монгол)",
    countryCode: "MN",
    dialCode: "976",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MN.svg",
  },
  {
    name: "Montenegro (Crna Gora)",
    countryCode: "ME",
    dialCode: "382",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/ME.svg",
  },
  {
    name: "Montserrat",
    countryCode: "MS",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MS.svg",
  },
  {
    name: "Morocco (‫المغرب‬‎)",
    countryCode: "MA",
    dialCode: "212",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MA.svg",
  },
  {
    name: "Mozambique (Moçambique)",
    countryCode: "MZ",
    dialCode: "258",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MZ.svg",
  },
  {
    name: "Myanmar (Burma) (မြန်မာ)",
    countryCode: "MM",
    dialCode: "95",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MM.svg",
  },
  {
    name: "Namibia (Namibië)",
    countryCode: "NA",
    dialCode: "264",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/NA.svg",
  },
  {
    name: "Nauru",
    countryCode: "NR",
    dialCode: "674",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/NR.svg",
  },
  {
    name: "Nepal (नेपाल)",
    countryCode: "NP",
    dialCode: "977",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/NP.svg",
  },
  {
    name: "Netherlands (Nederland)",
    countryCode: "NL",
    dialCode: "31",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/NL.svg",
  },
  {
    name: "New Caledonia (Nouvelle-Calédonie)",
    countryCode: "NC",
    dialCode: "687",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/NC.svg",
  },
  {
    name: "New Zealand",
    countryCode: "NZ",
    dialCode: "64",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/NZ.svg",
  },
  {
    name: "Nicaragua",
    countryCode: "NI",
    dialCode: "505",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/NI.svg",
  },
  {
    name: "Niger (Nijar)",
    countryCode: "NE",
    dialCode: "227",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/NE.svg",
  },
  {
    name: "Nigeria",
    countryCode: "NG",
    dialCode: "234",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/NG.svg",
  },
  {
    name: "Niue",
    countryCode: "NU",
    dialCode: "683",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/NU.svg",
  },
  {
    name: "Norfolk Island",
    countryCode: "NF",
    dialCode: "672",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/NF.svg",
  },
  {
    name: "North Korea (조선 민주주의 인민 공화국)",
    countryCode: "KP",
    dialCode: "850",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/KP.svg",
  },
  {
    name: "North Macedonia (Северна Македонија)",
    countryCode: "MK",
    dialCode: "389",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MK.svg",
  },
  {
    name: "Northern Mariana Islands",
    countryCode: "MP",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MP.svg",
  },
  {
    name: "Norway (Norge)",
    countryCode: "NO",
    dialCode: "47",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/NO.svg",
  },
  {
    name: "Oman (‫عُمان‬‎)",
    countryCode: "OM",
    dialCode: "968",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/OM.svg",
  },
  {
    name: "Pakistan (‫پاکستان‬‎)",
    countryCode: "PK",
    dialCode: "92",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/PK.svg",
  },
  {
    name: "Palau",
    countryCode: "PW",
    dialCode: "680",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/PW.svg",
  },
  {
    name: "Palestine (‫فلسطين‬‎)",
    countryCode: "PS",
    dialCode: "970",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/PS.svg",
  },
  {
    name: "Panama (Panamá)",
    countryCode: "PA",
    dialCode: "507",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/PA.svg",
  },
  {
    name: "Papua New Guinea",
    countryCode: "PG",
    dialCode: "675",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/PG.svg",
  },
  {
    name: "Paraguay",
    countryCode: "PY",
    dialCode: "595",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/PY.svg",
  },
  {
    name: "Peru (Perú)",
    countryCode: "PE",
    dialCode: "51",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/PE.svg",
  },
  {
    name: "Philippines",
    countryCode: "PH",
    dialCode: "63",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/PH.svg",
  },
  {
    name: "Poland (Polska)",
    countryCode: "PL",
    dialCode: "48",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/PL.svg",
  },
  {
    name: "Portugal",
    countryCode: "PT",
    dialCode: "351",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/PT.svg",
  },
  {
    name: "Puerto Rico",
    countryCode: "PR",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/PR.svg",
  },
  {
    name: "Qatar (‫قطر‬‎)",
    countryCode: "QA",
    dialCode: "974",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/QA.svg",
  },
  {
    name: "Réunion (La Réunion)",
    countryCode: "RE",
    dialCode: "262",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/RE.svg",
  },
  {
    name: "Romania (România)",
    countryCode: "RO",
    dialCode: "40",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/RO.svg",
  },
  {
    name: "Russia (Россия)",
    countryCode: "RU",
    dialCode: "7",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/RU.svg",
  },
  {
    name: "Rwanda",
    countryCode: "RW",
    dialCode: "250",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/RW.svg",
  },
  {
    name: "Saint Barthélemy",
    countryCode: "BL",
    dialCode: "590",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/BL.svg",
  },
  {
    name: "Saint Helena",
    countryCode: "SH",
    dialCode: "290",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SH.svg",
  },
  {
    name: "Saint Kitts and Nevis",
    countryCode: "KN",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/KN.svg",
  },
  {
    name: "Saint Lucia",
    countryCode: "LC",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/LC.svg",
  },
  {
    name: "Saint Martin (Saint-Martin (partie française))",
    countryCode: "MF",
    dialCode: "590",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/MF.svg",
  },
  {
    name: "Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)",
    countryCode: "PM",
    dialCode: "508",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/PM.svg",
  },
  {
    name: "Saint Vincent and the Grenadines",
    countryCode: "VC",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/VC.svg",
  },
  {
    name: "Samoa",
    countryCode: "WS",
    dialCode: "685",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/WS.svg",
  },
  {
    name: "San Marino",
    countryCode: "SM",
    dialCode: "378",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SM.svg",
  },
  {
    name: "São Tomé and Príncipe (São Tomé e Príncipe)",
    countryCode: "ST",
    dialCode: "239",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/ST.svg",
  },
  {
    name: "Saudi Arabia (‫المملكة العربية السعودية‬‎)",
    countryCode: "SA",
    dialCode: "966",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SA.svg",
  },
  {
    name: "Senegal (Sénégal)",
    countryCode: "SN",
    dialCode: "221",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SN.svg",
  },
  {
    name: "Serbia (Србија)",
    countryCode: "RS",
    dialCode: "381",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/RS.svg",
  },
  {
    name: "Seychelles",
    countryCode: "SC",
    dialCode: "248",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SC.svg",
  },
  {
    name: "Sierra Leone",
    countryCode: "SL",
    dialCode: "232",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SL.svg",
  },
  {
    name: "Singapore",
    countryCode: "SG",
    dialCode: "65",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SG.svg",
  },
  {
    name: "Sint Maarten",
    countryCode: "SX",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SX.svg",
  },
  {
    name: "Slovakia (Slovensko)",
    countryCode: "SK",
    dialCode: "421",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SK.svg",
  },
  {
    name: "Slovenia (Slovenija)",
    countryCode: "SI",
    dialCode: "386",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SI.svg",
  },
  {
    name: "Solomon Islands",
    countryCode: "SB",
    dialCode: "677",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SB.svg",
  },
  {
    name: "Somalia (Soomaaliya)",
    countryCode: "SO",
    dialCode: "252",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SO.svg",
  },
  {
    name: "South Africa",
    countryCode: "ZA",
    dialCode: "27",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/ZA.svg",
  },
  {
    name: "South Korea (대한민국)",
    countryCode: "KR",
    dialCode: "82",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/KR.svg",
  },
  {
    name: "South Sudan (‫جنوب السودان‬‎)",
    countryCode: "SS",
    dialCode: "211",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SS.svg",
  },
  {
    name: "Spain (España)",
    countryCode: "ES",
    dialCode: "34",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/ES.svg",
  },
  {
    name: "Sri Lanka (ශ්‍රී ලංකාව)",
    countryCode: "LK",
    dialCode: "94",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/LK.svg",
  },
  {
    name: "Sudan (‫السودان‬‎)",
    countryCode: "SD",
    dialCode: "249",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SD.svg",
  },
  {
    name: "Suriname",
    countryCode: "SR",
    dialCode: "597",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SR.svg",
  },
  {
    name: "Svalbard and Jan Mayen",
    countryCode: "SJ",
    dialCode: "47",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SJ.svg",
  },
  {
    name: "Sweden (Sverige)",
    countryCode: "SE",
    dialCode: "46",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SE.svg",
  },
  {
    name: "Switzerland (Schweiz)",
    countryCode: "CH",
    dialCode: "41",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/CH.svg",
  },
  {
    name: "Syria (‫سوريا‬‎)",
    countryCode: "SY",
    dialCode: "963",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/SY.svg",
  },
  {
    name: "Taiwan (台灣)",
    countryCode: "TW",
    dialCode: "886",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/TW.svg",
  },
  {
    name: "Tajikistan",
    countryCode: "TJ",
    dialCode: "992",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/TJ.svg",
  },
  {
    name: "Tanzania",
    countryCode: "TZ",
    dialCode: "255",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/TZ.svg",
  },
  {
    name: "Thailand (ไทย)",
    countryCode: "TH",
    dialCode: "66",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/TH.svg",
  },
  {
    name: "Timor-Leste",
    countryCode: "TL",
    dialCode: "670",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/TL.svg",
  },
  {
    name: "Togo",
    countryCode: "TG",
    dialCode: "228",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/TG.svg",
  },
  {
    name: "Tokelau",
    countryCode: "TK",
    dialCode: "690",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/TK.svg",
  },
  {
    name: "Tonga",
    countryCode: "TO",
    dialCode: "676",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/TO.svg",
  },
  {
    name: "Trinidad and Tobago",
    countryCode: "TT",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/TT.svg",
  },
  {
    name: "Tunisia (‫تونس‬‎)",
    countryCode: "TN",
    dialCode: "216",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/TN.svg",
  },
  {
    name: "Turkey (Türkiye)",
    countryCode: "TR",
    dialCode: "90",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/TR.svg",
  },
  {
    name: "Turkmenistan",
    countryCode: "TM",
    dialCode: "993",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/TM.svg",
  },
  {
    name: "Turks and Caicos Islands",
    countryCode: "TC",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/TC.svg",
  },
  {
    name: "Tuvalu",
    countryCode: "TV",
    dialCode: "688",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/TV.svg",
  },
  {
    name: "U.S. Virgin Islands",
    countryCode: "VI",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/VI.svg",
  },
  {
    name: "Uganda",
    countryCode: "UG",
    dialCode: "256",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/UG.svg",
  },
  {
    name: "Ukraine (Україна)",
    countryCode: "UA",
    dialCode: "380",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/UA.svg",
  },
  {
    name: "United Arab Emirates (‫الإمارات العربية المتحدة‬‎)",
    countryCode: "AE",
    dialCode: "971",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/AE.svg",
  },
  {
    name: "United Kingdom",
    countryCode: "GB",
    dialCode: "44",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/GB.svg",
  },
  {
    name: "United States",
    countryCode: "US",
    dialCode: "1",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/US.svg",
  },
  {
    name: "Uruguay",
    countryCode: "UY",
    dialCode: "598",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/UY.svg",
  },
  {
    name: "Uzbekistan (Oʻzbekiston)",
    countryCode: "UZ",
    dialCode: "998",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/UZ.svg",
  },
  {
    name: "Vanuatu",
    countryCode: "VU",
    dialCode: "678",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/VU.svg",
  },
  {
    name: "Vatican City (Città del Vaticano)",
    countryCode: "VA",
    dialCode: "39",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/VA.svg",
  },
  {
    name: "Venezuela",
    countryCode: "VE",
    dialCode: "58",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/VE.svg",
  },
  {
    name: "Vietnam (Việt Nam)",
    countryCode: "VN",
    dialCode: "84",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/VN.svg",
  },
  {
    name: "Wallis and Futuna (Wallis-et-Futuna)",
    countryCode: "WF",
    dialCode: "681",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/WF.svg",
  },
  {
    name: "Western Sahara (‫الصحراء الغربية‬‎)",
    countryCode: "EH",
    dialCode: "212",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/EH.svg",
  },
  {
    name: "Yemen (‫اليمن‬‎)",
    countryCode: "YE",
    dialCode: "967",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/YE.svg",
  },
  {
    name: "Zambia",
    countryCode: "ZM",
    dialCode: "260",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/ZM.svg",
  },
  {
    name: "Zimbabwe",
    countryCode: "ZW",
    dialCode: "263",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/ZW.svg",
  },
  {
    name: "Åland Islands",
    countryCode: "AX",
    dialCode: "358",
    icon: "http://purecatamphetamine.github.io/country-flag-icons/3x2/AX.svg",
  },
];
